[terminal.shell]
program = "nu"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.98

[window.padding]
x = 0
y = 0

[keyboard]

[terminal]
# Remap Ctrl+C to copy
#bindings = [{ key = "c", mods = "Alt", action = "Copy" },
#{ key = "v", mods = "Alt", action = "Paste" },
# Remap Ctrl+Shift+C to interrupt
#{ key = "c", mods = "Control|Shift",  chars = "\u0003" }
#]
