-- lazy.nvim
--
return {}
-- return {
--   "folke/snacks.nvim",
--   ---@type snacks.Config
--   opts = {
--     picker = {
--       sources = {
--         explorer = {
--           -- your explorer picker configuration comes here
--           -- or leave it empty to use the default settings
--           layout = { layout = { position = "right" } },
--         },
--         buffers = {
--           hidden = true,
--         },
--       },
--     },
--   },
-- }
